# Generated by Django 3.1.1 on 2021-04-09 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PesananModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=20)),
                ('jumlah_Ac', models.PositiveIntegerField()),
                ('alamat', models.TextField()),
                ('no_Telp', models.CharField(max_length=15)),
                ('tanggal', models.DateField(auto_now=True)),
                ('total', models.PositiveIntegerField()),
                ('slug_Pesanan', models.SlugField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='product.productmodel')),
            ],
        ),
    ]
