# Generated by Django 3.1.1 on 2021-04-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesananmodel',
            name='total',
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
