# Generated by Django 3.1.1 on 2021-04-12 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('pesanan', '0002_auto_20210409_2155'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pesananmodel',
            old_name='nama',
            new_name='kwitansi',
        ),
        migrations.RemoveField(
            model_name='pesananmodel',
            name='alamat',
        ),
        migrations.RemoveField(
            model_name='pesananmodel',
            name='no_Telp',
        ),
        migrations.AddField(
            model_name='pesananmodel',
            name='client',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='client.clientmodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesananmodel',
            name='total',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
