# Generated by Django 3.1.1 on 2021-04-15 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('product', '0002_auto_20210409_2155'),
        ('pesanan', '0003_auto_20210412_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesananmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.clientmodel', verbose_name='Nama Client'),
        ),
        migrations.AlterField(
            model_name='pesananmodel',
            name='kwitansi',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='pesananmodel',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='produk', to='product.productmodel'),
        ),
    ]
