# Generated by Django 3.1.1 on 2021-04-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0004_auto_20210415_2025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pesananmodel',
            options={'verbose_name': 'Pesanan', 'verbose_name_plural': 'Pesanan'},
        ),
    ]
