# Generated by Django 3.1.1 on 2021-04-21 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pesanan', '0005_auto_20210416_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='approvalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approve', models.BooleanField(default=False)),
                ('tgl_approve', models.DateField(blank=True, null=True)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='adminApprov', to=settings.AUTH_USER_MODEL)),
                ('pesanan', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pesanan', to='pesanan.pesananmodel')),
            ],
            options={
                'verbose_name': 'Approval',
                'verbose_name_plural': 'Approval Pesanan',
            },
        ),
    ]
