# Generated by Django 3.1.1 on 2021-04-21 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pesanan', '0006_approvalmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmodel',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='adminUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='pembayaranModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_pembayaran', models.CharField(max_length=30)),
                ('tgl_input', models.DateField(auto_now=True)),
                ('jumlah', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DP', 'UANG MUKA'), ('CICILAN', 'CICILAN'), ('LUNAS', 'LUNAS')], max_length=10)),
                ('keterangan', models.TextField()),
                ('tgl_pembayaran', models.DateField()),
                ('slug_pembayaran', models.SlugField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin', to=settings.AUTH_USER_MODEL)),
                ('pesanan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='payment', to='pesanan.pesananmodel')),
            ],
            options={
                'verbose_name': 'Pembayaran',
                'verbose_name_plural': 'Pembayaran',
            },
        ),
    ]
