# Generated by Django 3.1.1 on 2021-04-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0007_auto_20210421_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalmodel',
            name='slug_Approv',
            field=models.SlugField(default='exit'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='approvalmodel',
            name='keterangan',
            field=models.TextField(blank=True, null=True, verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='approvalmodel',
            name='tgl_approve',
            field=models.DateField(blank=True, null=True, verbose_name='Tanggal Approval'),
        ),
        migrations.AlterField(
            model_name='pembayaranmodel',
            name='jumlah',
            field=models.PositiveIntegerField(default=0, verbose_name='Jumlah Pembayaran'),
        ),
        migrations.AlterField(
            model_name='pembayaranmodel',
            name='no_pembayaran',
            field=models.CharField(max_length=30, verbose_name='Nomor Pembayaran'),
        ),
        migrations.AlterField(
            model_name='pembayaranmodel',
            name='tgl_input',
            field=models.DateField(auto_now=True, verbose_name='Tanggal Input'),
        ),
        migrations.AlterField(
            model_name='pembayaranmodel',
            name='tgl_pembayaran',
            field=models.DateField(verbose_name='Tanggal Pembayaran'),
        ),
    ]
