# Generated by Django 3.1.1 on 2021-04-26 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0008_auto_20210421_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesananmodel',
            name='Keterangan',
            field=models.TextField(default='Service'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pesananmodel',
            name='jumlah_Ac',
            field=models.PositiveIntegerField(verbose_name='Jumlah AC'),
        ),
        migrations.AlterField(
            model_name='pesananmodel',
            name='kwitansi',
            field=models.CharField(blank=True, max_length=20, verbose_name='Nomor Kwitansi'),
        ),
        migrations.AlterField(
            model_name='pesananmodel',
            name='tanggal',
            field=models.DateField(auto_now=True, verbose_name='Tanggal'),
        ),
        migrations.AlterField(
            model_name='pesananmodel',
            name='total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Pembayaran'),
        ),
    ]
