# Generated by Django 3.1.1 on 2021-04-26 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210426_2156'),
        ('pesanan', '0009_auto_20210426_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pesananmodel',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client', to='client.clientmodel', verbose_name='Nama Client'),
        ),
        migrations.AlterField(
            model_name='pesananmodel',
            name='jumlah_Ac',
            field=models.PositiveIntegerField(null=True, verbose_name='Jumlah AC'),
        ),
    ]
