# Generated by Django 3.1.1 on 2021-04-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0010_auto_20210426_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalmodel',
            name='pesanan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ApprovPesanan', to='pesanan.pesananmodel'),
        ),
    ]
