# Generated by Django 3.1.1 on 2021-04-15 13:40

from django.db import migrations, models
import eventContent.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventContentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_Content', models.CharField(max_length=50)),
                ('images_Content', models.ImageField(blank=True, upload_to=eventContent.models.upload_location)),
                ('keterangan_Content', models.TextField()),
                ('slug_Content', models.SlugField()),
            ],
        ),
    ]
