# Generated by Django 3.1.1 on 2021-04-16 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventContent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcontentmodel',
            name='admin',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='account.account'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventcontentmodel',
            name='tgl_upload',
            field=models.DateField(auto_now=True),
        ),
    ]
