# Generated by Django 3.1.1 on 2021-04-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventContent', '0002_auto_20210416_2139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventcontentmodel',
            options={'verbose_name': 'Event'},
        ),
    ]
