# Generated by Django 3.1.1 on 2021-04-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_Client', models.CharField(max_length=30)),
                ('noTelp_Client', models.CharField(max_length=15)),
                ('email_Client', models.EmailField(max_length=254)),
                ('alamat_Client', models.CharField(max_length=254)),
                ('kecamatan_Client', models.CharField(max_length=30)),
                ('kelurahan_Client', models.CharField(max_length=30)),
                ('kodePos_Client', models.CharField(max_length=30)),
                ('kota_Client', models.CharField(default='SURABAYA', max_length=30)),
                ('slug_Client', models.SlugField()),
            ],
        ),
    ]
