# Generated by Django 3.1.1 on 2021-04-21 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientmodel',
            options={'verbose_name': 'Client'},
        ),
    ]
