# Generated by Django 3.1.1 on 2021-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210421_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmodel',
            name='alamat_Client',
            field=models.CharField(max_length=254, verbose_name='Alamat'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='email_Client',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='kecamatan_Client',
            field=models.CharField(max_length=30, null=True, verbose_name='Kecamatan'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='kelurahan_Client',
            field=models.CharField(max_length=30, null=True, verbose_name='Kelurahan'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='kodePos_Client',
            field=models.CharField(max_length=30, null=True, verbose_name='Kode Pos'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='kota_Client',
            field=models.CharField(default='SURABAYA', max_length=30, null=True, verbose_name='Kota'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='nama_Client',
            field=models.CharField(max_length=30, verbose_name='Nama'),
        ),
        migrations.AlterField(
            model_name='clientmodel',
            name='noTelp_Client',
            field=models.CharField(max_length=15, verbose_name='Phone'),
        ),
    ]
