# Generated by Django 3.1.1 on 2021-04-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210416_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='jabatan',
            field=models.CharField(choices=[('ADMIN', 'ADMIN'), ('TEKNISI', 'TEKNISI')], default='ADMIN', max_length=8),
            preserve_default=False,
        ),
    ]
