# Generated by Django 3.1.1 on 2021-04-21 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pesanan', '0007_auto_20210421_2124'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SPKModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_SPK', models.CharField(max_length=30)),
                ('tgl_input', models.DateField(auto_now=True)),
                ('tgl_pengerjaan', models.DateField()),
                ('keterangan', models.TextField()),
                ('status', models.CharField(choices=[('PANDING', 'PANDING'), ('CANCEL', 'CANCEL'), ('SELESAI', 'SELESAI')], max_length=10)),
                ('slug_SPK', models.SlugField()),
                ('approval', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval', to='pesanan.approvalmodel')),
                ('teknisi', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teknisiUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Surat Perintah Kerja',
                'verbose_name_plural': 'Surat Perintah Kerja',
            },
        ),
    ]
