# Generated by Django 3.1.1 on 2021-04-21 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SPK_teknisi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spkmodel',
            name='keterangan',
            field=models.TextField(verbose_name='Keterangan'),
        ),
        migrations.AlterField(
            model_name='spkmodel',
            name='no_SPK',
            field=models.CharField(max_length=30, verbose_name='Nomor SPK'),
        ),
        migrations.AlterField(
            model_name='spkmodel',
            name='teknisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='teknisiUser', to=settings.AUTH_USER_MODEL, verbose_name='Teknisi'),
        ),
        migrations.AlterField(
            model_name='spkmodel',
            name='tgl_input',
            field=models.DateField(auto_now=True, verbose_name='Tanggal Input'),
        ),
        migrations.AlterField(
            model_name='spkmodel',
            name='tgl_pengerjaan',
            field=models.DateField(verbose_name='Tanggal Pengerjaan'),
        ),
    ]
