# Generated by Django 3.1.1 on 2021-04-26 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SPK_teknisi', '0002_auto_20210421_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spkmodel',
            name='no_SPK',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nomor SPK'),
        ),
        migrations.AlterField(
            model_name='spkmodel',
            name='tgl_pengerjaan',
            field=models.DateField(auto_now=True, verbose_name='Tanggal Pengerjaan'),
        ),
    ]
