# Generated by Django 3.1.1 on 2021-04-29 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pesanan', '0011_auto_20210429_2239'),
        ('SPK_teknisi', '0003_auto_20210426_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spkmodel',
            name='approval',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approvalSPK', to='pesanan.approvalmodel'),
        ),
        migrations.AlterField(
            model_name='spkmodel',
            name='status',
            field=models.CharField(choices=[('PENDING', 'ON PROGRESS'), ('CANCEL', 'CANCEL'), ('SELESAI', 'SELESAI')], max_length=10),
        ),
    ]
