# Generated by Django 3.1.1 on 2021-04-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_Product', models.CharField(max_length=30)),
                ('keterangan_Product', models.TextField()),
                ('harga_Product', models.PositiveIntegerField()),
                ('slug_Product', models.SlugField(editable=False)),
            ],
        ),
    ]
