# Generated by Django 3.1.1 on 2021-04-09 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='harga_Product',
            new_name='hargaProduct',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='keterangan_Product',
            new_name='keteranganProduct',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='nama_Product',
            new_name='namaProduct',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='slug_Product',
            new_name='slugProduct',
        ),
    ]
