# Generated by Django 3.1.1 on 2021-04-16 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210409_2155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmodel',
            options={'verbose_name': 'Product'},
        ),
    ]
